### PR TITLE
Interactive selector for choosing the CRN on which to run the instance  + display Confidential compute support

### PR DESCRIPTION
**Pull request by olethanh**
- Add an interactive selector for choosing the CRN on which to run (in case of PAYG or confidential) This is using textual
- Retrieve if the CRN support confidential computing and retrieve it

[Screencast from 2024-07-15 10-03-42.webm](https://github.com/user-attachments/assets/bb392ac2-9e79-4cf4-8866-7085e4045418)

### CODE REVIEW

**Comment by Psycojoker** [comment]
Lyam will take the lead of this PR.

**Comment by 1yam** [comment]
@olethanh I’ve addressed all the mypy errors, and everything looks good to me now. Are there any other aspects or improvements you think might be needed?

**Comment by olethanh** [comment]
@1yam It is good for me, thanks a lot for the help

**Review by Psycojoker — APPROVED** [review]
Appart from this general comment LGTM (but idk the textual lib yet)

**Comment by olethanh** [comment]
@Psycojoker Added the debug log

**Pull request merged**
