### PR TITLE
 * Fix CLI regression

### PR DESCRIPTION
**Pull request by aliel**
WIP

### CODE REVIEW

**Comment by hoh** [comment]
@aliel why is this a draft ?

**Comment by MHHukiewitz** [comment]
@hoh I think he wanted to test the other commands as well for regressions. Writing integration tests with for all commands is on my TODO list, which will do the same.

**Comment by MHHukiewitz** [comment]
I'd propose to merge it now and release a new version with the regression fix ASAP

**Comment by MHHukiewitz** [comment]
Yup, seems like it

**Review by nesitor — APPROVED** [review]

**Pull request merged**
